"""Tests de migraciones contra Postgres real.

Los demás tests corren sobre SQLite en memoria con `create_all`, que no prueba
nada de Alembic. Estos sí: verifican que una migración no rompa una base con
datos, que el esquema migrado coincida con los modelos y que el puente para
bases pre-Alembic no re-cree tablas.

Necesitan un servidor Postgres. Se activan con:

    MIGRATIONS_TEST_DATABASE_URL=postgresql+psycopg://budget:budget@localhost:5432/postgres \\
        uv run pytest tests/test_migrations.py

Sin esa variable se saltan (así `uv run pytest` sigue siendo offline y rápido).
En CI la provee el servicio `db` del workflow. Cada test corre contra una base
recién creada y la borra al terminar: nunca tocan la base apuntada por la URL.
"""

import os
from collections.abc import Iterator

import pytest
from sqlalchemy import create_engine, inspect, text
from sqlalchemy.exc import IntegrityError

from alembic import command
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from app import db_bootstrap
from app.db_bootstrap import INITIAL_REVISION, alembic_config

ADMIN_URL = os.environ.get("MIGRATIONS_TEST_DATABASE_URL")

# En CI, saltarse estos tests sería un falso verde: el job los pide con
# MIGRATIONS_TEST_REQUIRED=1 y sin base preferimos que reviente al recolectar.
if not ADMIN_URL and os.environ.get("MIGRATIONS_TEST_REQUIRED") == "1":
    raise RuntimeError(
        "MIGRATIONS_TEST_REQUIRED=1 pero falta MIGRATIONS_TEST_DATABASE_URL: "
        "el servicio de Postgres no llegó."
    )

pytestmark = pytest.mark.skipif(
    not ADMIN_URL,
    reason="requiere MIGRATIONS_TEST_DATABASE_URL apuntando a un Postgres",
)

#: Tablas de la aplicación, sin contar `alembic_version`.
APP_TABLES = {
    "households",
    "users",
    "invitations",
    "accounts",
    "categories",
    "transactions",
    "attachments",
    "recurring_rules",
    "budgets",
    "savings_goals",
    "transfer_groups",
}


def _head_revision() -> str:
    script = ScriptDirectory.from_config(alembic_config(ADMIN_URL))
    return script.get_current_head()


@pytest.fixture(name="database_url")
def database_url_fixture(request: pytest.FixtureRequest) -> Iterator[str]:
    """Crea una base vacía para el test y la borra al final."""
    # Nombre derivado del test: legible si algo queda colgado.
    name = "mig_" + "".join(
        c if c.isalnum() else "_" for c in request.node.name.lower()
    )[:50]

    admin = create_engine(ADMIN_URL, isolation_level="AUTOCOMMIT")
    with admin.connect() as connection:
        connection.execute(text(f'DROP DATABASE IF EXISTS "{name}" WITH (FORCE)'))
        connection.execute(text(f'CREATE DATABASE "{name}"'))

    url = ADMIN_URL.rsplit("/", 1)[0] + "/" + name
    try:
        yield url
    finally:
        with admin.connect() as connection:
            connection.execute(text(f'DROP DATABASE IF EXISTS "{name}" WITH (FORCE)'))
        admin.dispose()


def _tables(database_url: str) -> set[str]:
    engine = create_engine(database_url)
    try:
        with engine.connect() as connection:
            return set(inspect(connection).get_table_names())
    finally:
        engine.dispose()


def _scalar(database_url: str, sql: str):
    engine = create_engine(database_url)
    try:
        with engine.connect() as connection:
            return connection.execute(text(sql)).scalar()
    finally:
        engine.dispose()


def _seed_household_and_user(database_url: str, email: str = "ana@example.com") -> None:
    """Inserta datos con SQL crudo: el ORM de hoy no sirve para simular una base
    vieja (tiene columnas que en esa revisión aún no existen)."""
    engine = create_engine(database_url)
    try:
        with engine.begin() as connection:
            connection.execute(
                text(
                    "INSERT INTO households (id, name, currency_code) "
                    "VALUES ('h1', 'Casa Ana', 'MXN')"
                )
            )
            connection.execute(
                text(
                    "INSERT INTO households (id, name, currency_code) "
                    "VALUES ('h_orphan', 'Casa Vacía', 'MXN')"
                )
            )
            connection.execute(
                text(
                    "INSERT INTO users (id, email, hashed_password, name, household_id, created_at) "
                    "VALUES ('u1', :email, 'hash', 'Ana', 'h1', '2000-01-01')"
                ),
                {"email": email},
            )
            connection.execute(
                text(
                    "INSERT INTO users (id, email, hashed_password, name, household_id, created_at) "
                    "VALUES ('u2', 'luis@example.com', 'hash', 'Luis', 'h1', '2100-01-01')"
                )
            )
    finally:
        engine.dispose()


def _seed_recurring_rule(database_url: str) -> None:
    """Una regla recurrente con SQL crudo en la revisión previa a la de
    recurrentes: la tabla existía pero sin `created_by_id` ni `anchor_day`."""
    engine = create_engine(database_url)
    try:
        with engine.begin() as connection:
            connection.execute(
                text(
                    "INSERT INTO accounts (id, household_id, name, kind, opening_balance) "
                    "VALUES ('a1', 'h1', 'Débito', 'debit', 0)"
                )
            )
            connection.execute(
                text(
                    "INSERT INTO categories (id, household_id, name, icon, color, type, active) "
                    "VALUES ('c1', 'h1', 'Casa', 'home', '#30b0c7', 'expense', true)"
                )
            )
            connection.execute(
                text(
                    "INSERT INTO recurring_rules "
                    "(id, household_id, type, amount, category_id, account_id, "
                    " frequency, next_run_date, active) "
                    "VALUES ('r1', 'h1', 'expense', 1200, 'c1', 'a1', "
                    " 'monthly', '2026-07-01', true)"
                )
            )
    finally:
        engine.dispose()


def test_upgrade_head_crea_el_esquema_completo(database_url: str) -> None:
    command.upgrade(alembic_config(database_url), "head")

    tables = _tables(database_url)
    assert APP_TABLES <= tables, f"faltan tablas: {APP_TABLES - tables}"
    assert "alembic_version" in tables
    assert _scalar(database_url, "SELECT version_num FROM alembic_version") == _head_revision()


def test_esquema_migrado_coincide_con_los_modelos(database_url: str) -> None:
    """`alembic check`: si alguien toca models.py y no genera la migración, esto
    falla. Es el gate que evita que producción quede sin una columna."""
    command.upgrade(alembic_config(database_url), "head")

    try:
        command.check(alembic_config(database_url))
    except AutogenerateDiffsDetected as exc:
        pytest.fail(
            "models.py tiene cambios sin migración; corre "
            f"`uv run alembic revision --autogenerate`. Diff: {exc}"
        )


def test_downgrade_base_deja_la_base_limpia(database_url: str) -> None:
    config = alembic_config(database_url)
    command.upgrade(config, "head")
    command.downgrade(config, "base")

    assert _tables(database_url) - {"alembic_version"} == set()


def test_upgrade_downgrade_upgrade_es_reversible(database_url: str) -> None:
    """Cada migración debe poder ir y volver: sin esto, un rollback en
    producción es un viaje sin retorno."""
    config = alembic_config(database_url)
    command.upgrade(config, "head")
    command.downgrade(config, "base")
    command.upgrade(config, "head")

    assert APP_TABLES <= _tables(database_url)


def test_los_datos_sobreviven_a_las_migraciones(database_url: str) -> None:
    """El caso que importa: una base con datos que salta de la primera revisión
    a head sin perder filas, y con el backfill del flag aplicado."""
    config = alembic_config(database_url)
    command.upgrade(config, INITIAL_REVISION)
    _seed_household_and_user(database_url)

    command.upgrade(config, "head")

    assert _scalar(database_url, "SELECT count(*) FROM users") == 2
    assert _scalar(database_url, "SELECT name FROM users WHERE id = 'u1'") == "Ana"
    assert _scalar(database_url, "SELECT count(*) FROM households") == 2
    assert _scalar(database_url, "SELECT count(*) FROM accounts WHERE owner_id IS NOT NULL") == 0
    assert _scalar(database_url, "SELECT owner_id FROM households WHERE id = 'h1'") == "u1"
    assert _scalar(
        database_url, "SELECT owner_id FROM households WHERE id = 'h_orphan'"
    ) is None
    engine = create_engine(database_url)
    try:
        with pytest.raises(IntegrityError):
            with engine.begin() as connection:
                connection.execute(
                    text("UPDATE households SET owner_id = 'u2' WHERE id = 'h_orphan'")
                )
    finally:
        engine.dispose()
    # La migración del onboarding marca a los usuarios que ya existían: si no,
    # verían un wizard que no les toca.
    assert _scalar(
        database_url, "SELECT onboarding_completed_at FROM users WHERE id = 'u1'"
    ) is not None


def test_el_backfill_de_recurrentes_no_deja_reglas_sin_autor(database_url: str) -> None:
    """`created_by_id` es NOT NULL. La tabla nunca fue escribible, así que en la
    práctica está vacía, pero si una base tuviera filas el backfill tiene que
    resolverlas al miembro más antiguo del hogar en vez de tumbar el arranque."""
    config = alembic_config(database_url)
    command.upgrade(config, "673ed5f3d911")
    _seed_household_and_user(database_url)
    _seed_recurring_rule(database_url)

    command.upgrade(config, "head")

    assert _scalar(database_url, "SELECT count(*) FROM recurring_rules") == 1
    assert _scalar(database_url, "SELECT created_by_id FROM recurring_rules") == "u1"
    # anchor_day queda NULL: la regla vieja no declaraba día ancla y el avance
    # cae en el día de next_run_date.
    assert _scalar(database_url, "SELECT anchor_day FROM recurring_rules") is None


def test_puente_pre_alembic_no_recrea_ni_borra_nada(database_url: str) -> None:
    """Simula el despliegue real que existía antes de Alembic: esquema en la
    revisión inicial, con datos, y sin `alembic_version`. El bootstrap debe
    stampear y seguir migrando, no re-crear tablas."""
    command.upgrade(alembic_config(database_url), INITIAL_REVISION)
    _seed_household_and_user(database_url)

    engine = create_engine(database_url)
    try:
        with engine.begin() as connection:
            connection.execute(text("DROP TABLE alembic_version"))
    finally:
        engine.dispose()
    assert db_bootstrap._is_pre_alembic_database(database_url)

    db_bootstrap.main(database_url)

    assert _scalar(database_url, "SELECT version_num FROM alembic_version") == _head_revision()
    # Los datos siguen ahí → no re-creó las tablas
    assert _scalar(database_url, "SELECT name FROM users WHERE id = 'u1'") == "Ana"
    assert _scalar(
        database_url, "SELECT onboarding_completed_at FROM users WHERE id = 'u1'"
    ) is not None


def test_bootstrap_es_idempotente(database_url: str) -> None:
    """Cada arranque del contenedor lo ejecuta: correrlo dos veces no debe
    fallar ni mover nada."""
    db_bootstrap.main(database_url)
    first = _scalar(database_url, "SELECT onboarding_completed_at FROM users LIMIT 1")

    db_bootstrap.main(database_url)

    assert _scalar(database_url, "SELECT version_num FROM alembic_version") == _head_revision()
    assert _scalar(database_url, "SELECT onboarding_completed_at FROM users LIMIT 1") == first


def test_base_vacia_no_se_confunde_con_pre_alembic(database_url: str) -> None:
    assert not db_bootstrap._is_pre_alembic_database(database_url)
